# Generated by Django 4.2 on 2023-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
