# Generated by Django 4.1 on 2023-04-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
