# Generated by Django 4.1 on 2023-04-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0003_blog_image_postcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
