# Generated by Django 4.1 on 2023-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date_Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
