# Generated by Django 4.1 on 2023-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0005_blog_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='Date_Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
