# Generated by Django 4.1 on 2023-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0006_postcategory_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='comment')),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
