# Generated by Django 4.1 on 2023-05-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0007_comment_alter_postcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Last_Name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='First_Name',
            new_name='name',
        ),
    ]
