# Generated by Django 4.1 on 2023-05-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0008_rename_last_name_comment_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
