# Generated by Django 4.1 on 2023-05-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0009_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='comment')),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('postCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentPost', to='klog.postcategory')),
            ],
        ),
    ]
