# Generated by Django 4.1 on 2023-05-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0012_alter_commentblog_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentBlog',
        ),
    ]
