# Generated by Django 4.1 on 2023-05-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0013_delete_commentblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klog.blog')),
            ],
        ),
    ]
