# Generated by Django 4.1 on 2023-05-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0014_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='postCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klog.postcategory'),
        ),
    ]
